name: ambient_sound_app
description: A Flutter app that plays ambient sounds.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # audioplayers foi removido para evitar conflito de canal de Ã¡udio
  shared_preferences: ^2.5.4
  audio_service: ^0.18.18
  just_audio: ^0.10.5
  easy_localization: ^3.0.7

dev_dependencies: 
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
    - assets/translations/